### ISSUE TITLE
Dumping issue when using Schema().dump(obj)

### ISSUE THREAD

**Issue by chespinoza** [lovasoa/marshmallow_dataclass#125]
Hi folks, thanks for marshmallow_dataclass.
I've got an issue when using the `Schema().dump(obj)` serialisation way which doesn't happen when I create an obj instance using `class_schema`, for instance if I have this schema:

```python
import typing as T
from dataclasses import field
from decimal import Decimal

import marshmallow as mm
import marshmallow_dataclass as mmdc


class BaseSchema(mm.Schema):
    SKIP_VALUES = {None}

    @mm.post_dump
    def remove_skip_values(self, data, many):
        return {
            key: value for key, value in data.items() if value not in self.SKIP_VALUES
        }


@mmdc.add_schema(base_schema=BaseSchema)
@mmdc.dataclass
class Item:
    key: str
    val: str
    Schema: T.ClassVar[T.Type[mm.Schema]] = mm.Schema


@mmdc.add_schema(base_schema=BaseSchema)
@mmdc.dataclass
class Items:
    other: T.Optional[str]
    items: T.List[Item] = field(default_factory=list)
    Schema: T.ClassVar[T.Type[mm.Schema]] = mm.Schema
```
Using `class_schema`
```python
data = {
    "items": [{"key":"any key", "val": "any value"}]
}


itemsSchema = mmdc.class_schema(Items)()
items = itemsSchema.load(data)
print(itemsSchema.dump(items))
```
There is no problem, it prints `{'other': None, 'items': [{'key': 'any key', 'val': 'any value'}]}` which is what I'd expect but if I try to use the short way described in the Readme:

```python
items = Items.Schema().load(data)
print(Items.Schema().dump(items))
```
It throws a TypeError: 

```
Traceback (most recent call last):
  File "/Users/christian/Dev/thonny_stuff/test_schemas.py", line 47, in <module>
    print(Items.Schema().dump(items))
  File "/Users/christian/Library/Python/3.7/lib/python/site-packages/marshmallow/schema.py", line 563, in dump
    POST_DUMP, result, many=many, original_data=obj
  File "/Users/christian/Library/Python/3.7/lib/python/site-packages/marshmallow/schema.py", line 1069, in _invoke_dump_processors
    tag, pass_many=False, data=data, many=many, original_data=original_data
  File "/Users/christian/Library/Python/3.7/lib/python/site-packages/marshmallow/schema.py", line 1227, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "/Users/christian/Dev/thonny_stuff/test_schemas.py", line 15, in remove_skip_values
    key: value for key, value in data.items() if value not in self.SKIP_VALUES
  File "/Users/christian/Dev/thonny_stuff/test_schemas.py", line 15, in <dictcomp>
    key: value for key, value in data.items() if value not in self.SKIP_VALUES
TypeError: unhashable type: 'list'
```
I'm having this issue with:
Python 3.7.9 
marshmallow = 3.9.1
marshmallow_dataclass =  8.3.0

and 
Python 3.7.1
marshmallow = "3.8.0"
marshmallow-dataclass = "^8.3.0"

Probably I'm doing something wrong, any feedback would be appreciated.
Thanks.

**Comment by lovasoa** [comment]
You forgot to pass the `base_schema` to `mmdc.class_schema`. Your first example should look like:

```python
        items_schema = mmdc.class_schema(Items, base_schema=BaseSchema)()
```

The bug is in your code. `value not in self.SKIP_VALUES` is incorrect because value may not be hashable. in your case it's a list.


```python
>>> [] in {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'

```
