### ISSUE TITLE
TypeError: Object of type Decimal is not JSON serializable

### ISSUE THREAD

**Issue by greenkey** [lovasoa/marshmallow_dataclass#138]
I find this error when I'm trying to serialise a `dataclass` with a `Decimal` field, I think this should be handled by `marshmallow_dataclass`.
I could not find this issue anywhere in the Internet, so here I am asking you what I'm doing wrong:

```
from dataclasses import dataclass
import datetime
from decimal import Decimal
import marshmallow_dataclass

@dataclass
class AccountBalance:
    entry_date: datetime.date
    balance: Decimal

b = AccountBalance(datetime.date.today(), Decimal("123.45"))

marshmallow_dataclass.class_schema(AccountBalance)().dumps(b)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "~/Projects/myproject/.venv/lib/python3.8/site-packages/marshmallow/schema.py", line 582, in dumps
    return self.opts.render_module.dumps(serialized, *args, **kwargs)
  File "~/.pyenv/versions/3.8.0/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "~/.pyenv/versions/3.8.0/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "~/.pyenv/versions/3.8.0/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "~/.pyenv/versions/3.8.0/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable
```

These are the versions I'm using:
```
$ pip freeze | grep marsh          
marshmallow==3.11.1
marshmallow-dataclass==8.4.1
marshmallow-enum==1.5.1
$ python -V
Python 3.8.0
```

**Comment by lovasoa** [comment]
Please refer to marshmallow's documentation: https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Decimal

**Comment by greenkey** [comment]
Thank you, I missed that.
