### ISSUE TITLE
validating field values after the dataclass object is created with the right field values?

### ISSUE THREAD

**Issue by sarimmehdi** [lovasoa/marshmallow_dataclass#176]
I want to do post-creation validation for a dataclass object. For example, if a dataclass object is created using the correct values but then, after its creation, the user tries to supply the wrong value to one of its fields, I want the validation mechanism to kick in place (as it does during creation time when the wrong types of values are supplied to the constructor for the dataclass). Below is an example:

```
from marshmallow import validate
from dataclasses import dataclass, field
import marshmallow_dataclass

@dataclass
class TestClass:
     test_field: int = field(metadata={'validate': validate.Range(min=0)})

test_schema = marshmallow_dataclass.class_schema(TestClass)()

test_object: TestClass = test_schema.load({'test_field': 1})    # this works fine

# I want this to throw an error to let me know that I am supplying a negative value to a field which requires a positive one
test_object.test_field = -1
```

**Comment by njmei** [comment]
@sarimmehdi You could override the `__setattr__` method and have it call the `validate` method of the `Schema` attribute that all `marshmallow_dataclass.dataclass`es will have. See this modified example:

```
from typing import Any
from marshmallow import ValidationError
from dataclasses import field
import marshmallow_dataclass

@marshmallow_dataclass.dataclass
class TestClass:
    test_field: int = field(metadata={'validate': validate.Range(min=0)})
            
    def __setattr__(self, name: str, value: Any):
        errors = self.Schema().validate(data={name: value}, partial=True)
        if any(errors):
            raise ValidationError(errors)
        super().__setattr__(name, value)

test_schema = marshmallow_dataclass.class_schema(TestClass)()

test_object: TestClass = test_schema.load({'test_field': 1})    # this works fine

test_object.test_field = -1
```

This throws the following for me:

```
ValidationError: {'test_field': ['Must be greater than or equal to 0.']}
```

**Comment by sarimmehdi** [comment]
Thank you, that solution worked

**Comment by sarimmehdi** [comment]
@njmei I am reopening this issue since your approach does not work for nested dataclass objects. Here is the sample code I used to check:

```
from typing import Any
from marshmallow import ValidationError, validate
from dataclasses import field
import marshmallow_dataclass


@marshmallow_dataclass.dataclass
class TestInnerClass:
    inner_test_field: str = field(metadata={'validate': validate.OneOf(['val1', 'val2'])})
    
    def __setattr__(self, name: str, value: Any):
        errors = self.Schema().validate(data={name: value}, partial=True)
        if any(errors):
            raise ValidationError(errors)
        super().__setattr__(name, value)


@marshmallow_dataclass.dataclass
class TestClass:
    test_field: int = field(metadata={'validate': validate.Range(min=0)})
    test_inner_class: TestInnerClass
            
    def __setattr__(self, name: str, value: Any):
        errors = self.Schema().validate(data={name: value}, partial=True)
        if any(errors):
            raise ValidationError(errors)
        super().__setattr__(name, value)

test_schema = marshmallow_dataclass.class_schema(TestClass)()

test_object: TestClass = test_schema.load({'test_field': 1, 'test_inner_class': {'inner_test_field': 'val1'}})

test_object.test_field = -1
test_object.test_inner_class.inner_test_field = 'val3'
```
Below is the stack trace of the error:

```
Traceback (most recent call last):
  File "/home/muhammadmehdi/ALL_PROJECTS/memex/test.py", line 31, in <module>
    test_object: TestClass = test_schema.load({'test_field': 1, 'test_inner_class': {'inner_test_field': 'val1'}})
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 644, in load
    return clazz(**all_loaded)
  File "<string>", line 4, in __init__
  File "/home/muhammadmehdi/ALL_PROJECTS/memex/test.py", line 26, in __setattr__
    raise ValidationError(errors)
marshmallow.exceptions.ValidationError: {'test_inner_class': {'_schema': ['Invalid input type.']}}
```

**Comment by sarimmehdi** [comment]
It turns out that value is supposed to be a JSON string but I am passing a class object so I need to serialize it to a string. Here is the code for anyone who is facing a similar problem with nested classes:

```
from marshmallow import ValidationError, validate
from dataclasses import field
import marshmallow_dataclass


@marshmallow_dataclass.dataclass
class TestInnerClass:
    inner_test_field: str = field(metadata={'validate': validate.OneOf(['val1', 'val2'])})
    
    def __setattr__(self, name: str, value: str):
        errors = self.Schema().validate(data={name: value}, partial=True)
        if any(errors):
            raise ValidationError(errors)
        super().__setattr__(name, value)


@marshmallow_dataclass.dataclass
class TestClass:
    test_field: int = field(metadata={'validate': validate.Range(min=0)})
    test_inner_class: TestInnerClass
            
    def __setattr__(self, name: str, value: TestInnerClass):
        if type(value) == TestInnerClass:
            schema = marshmallow_dataclass.class_schema(type(value))()
            errors = self.Schema().validate(data={name: schema.dump(value)}, partial=True) 
        else:
            errors = self.Schema().validate(data={name: value}, partial=True)
        if any(errors):
            raise ValidationError(errors)
        super().__setattr__(name, value)

test_schema = marshmallow_dataclass.class_schema(TestClass)()

test_object: TestClass = test_schema.load({'test_field': 1, 'test_inner_class': {'inner_test_field': 'val1'}})

try:
    test_object.test_field = -1
except ValidationError as e:
    print(e)
    
try:
    test_object.test_inner_class.inner_test_field = 'val3'
except ValidationError as e:
    print(e)
```
