### ISSUE TITLE
str | None fails

### ISSUE THREAD

**Issue by hydrargyrum** [lovasoa/marshmallow_dataclass#226]
With these versions:

```
marshmallow==3.19.0
marshmallow-dataclass==8.5.10
marshmallow-enum==1.5.1
marshmallow-oneofschema==2.1.0
```

The following snippet breaks:

```python
from typing import Optional, Union

from marshmallow_dataclass import dataclass


@dataclass
class WithOptional:
    id: Optional[str] = None


@dataclass
class WithUnion:
    id: Union[str, None]


@dataclass
class WithOr:
    id: str | None = None



print(WithOptional.Schema().load({}))
print(WithUnion.Schema().load({}))
print(WithOr.Schema().load({}))
```

with error:

```
WithOptional(id=None)
WithUnion(id=None)
Traceback (most recent call last):
  File "/home/.../marshbug.py", line 24, in <module>
    print(WithOr.Schema().load({}))
  File "/home/.../venv/lib/python3.10/site-packages/marshmallow_dataclass/lazy_class_attribute.py", line 33, in __get__
    setattr(cls, self.name, self.func())
  File "/home/.../venv/lib/python3.10/site-packages/marshmallow_dataclass/__init__.py", line 357, in class_schema
    return _internal_class_schema(clazz, base_schema, clazz_frame)
  File "/home/x/dev/core/venv/lib/python3.10/site-packages/marshmallow_dataclass/__init__.py", line 403, in _internal_class_schema
    attributes.update(
  File "/home/.../venv/lib/python3.10/site-packages/marshmallow_dataclass/__init__.py", line 406, in <genexpr>
    field_for_schema(
  File "/home/.../venv/lib/python3.10/site-packages/marshmallow_dataclass/__init__.py", line 734, in field_for_schema
    or _internal_class_schema(typ, base_schema, typ_frame)
  File "/home/.../venv/lib/python3.10/site-packages/marshmallow_dataclass/__init__.py", line 368, in _internal_class_schema
    _RECURSION_GUARD.seen_classes[clazz] = clazz.__name__
AttributeError: 'types.UnionType' object has no attribute '__name__'. Did you mean: '__ne__'?
```

**Comment by otonnesen** [comment]
I was unable to reproduce on python 3.10.8 with marshmallow-dataclass==8.5.10. Reverting to 8.5.9 produces the same output that you pasted above though. For reference:
```
(venv) $ cat requirements.txt
marshmallow==3.19.0
marshmallow-dataclass==8.5.10
marshmallow-enum==1.5.1
marshmallow-oneofschema==2.1.0

(venv) $ pip install -r requirements.txt
Requirement already satisfied: marshmallow==3.19.0 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (3.19.0)
...

(venv) $ pip freeze
marshmallow==3.19.0
marshmallow-dataclass==8.5.10
marshmallow-enum==1.5.1
marshmallow-oneofschema==2.1.0
mypy-extensions==0.4.3
packaging==22.0
typing-inspect==0.8.0
typing_extensions==4.4.0

(venv) $ python -V
Python 3.10.8

(venv) $ python test.py
WithOptional(id=None)
WithUnion(id=None)
WithOr(id=None)

```

**Comment by dairiki** [comment]
> I was unable to reproduce on python 3.10.8 with marshmallow-dataclass==8.5.10. Reverting to 8.5.9 produces the same output that you pasted above though.

PR #219, included as of release 8.5.10 should (at least, in theory) support the `str | None` notation.
(There is even a [regression test](https://github.com/lovasoa/marshmallow_dataclass/blob/2fc21d2c5788a1c1f50ebd00b9133a09fe077a16/tests/test_union.py#L186) for it.)

**Comment by hydrargyrum** [comment]
Ok the issue seems when this version is pinned: `typing-inspect==0.7.1`

**Comment by otonnesen** [comment]
I see. I believe that's sort of expected since support for UnionType was only added [here](https://github.com/ilevkivskyi/typing_inspect/pull/87) in typing-inspect v0.8.0.

It seems that marshmallow-dataclass only specifies typing-inspect>=0.7.1 in its setup.py, so I think this actually is a bug after all.

**Comment by dairiki** [comment]
> It seems that marshmallow-dataclass only specifies typing-inspect>=0.7.1 in its setup.py, so I think this actually is a bug after all.

I've just pushed 1d0f019cc5b85e6e940669962dda84c300a717ea which pins `typing-inspect>=0.8.0`.

Thanks, @hydrargyrum and @otonnesen, for the report and diagnosis.

Let me know if there's a need for an immediate new release (of marshmallow-dataclass), otherwise, I'll wait until there are more changes before making the next release.
