### ISSUE TITLE
Error when using default or default_factory

### ISSUE THREAD

**Issue by KoHcoJlb** [lovasoa/marshmallow_dataclass#3]
```
import dataclasses as dc
from marshmallow_dataclass import add_schema

@add_schema
@dc.dataclass
class User:
    id: str = dc.field(default=None)
```

```
Traceback (most recent call last):
  File "C:/t/projects/python/src/marshmallow_test.py", line 32, in <module>
    @dataclass
  File "C:\t\programs\python\python37\lib\site-packages\marshmallow_dataclass\__init__.py", line 77, in dataclass
    return add_schema(dataclasses.dataclass(clazz))
  File "C:\t\programs\python\python37\lib\site-packages\marshmallow_dataclass\__init__.py", line 93, in add_schema
    clazz.Schema = class_schema(clazz)
  File "C:\t\programs\python\python37\lib\site-packages\marshmallow_dataclass\__init__.py", line 193, in class_schema
    for field in fields
  File "C:\t\programs\python\python37\lib\site-packages\marshmallow_dataclass\__init__.py", line 194, in <dictcomp>
    if field.init
  File "C:\t\programs\python\python37\lib\site-packages\marshmallow_dataclass\__init__.py", line 255, in field_for_schema
    return _native_to_marshmallow[typ](**metadata)
  File "C:\t\programs\python\python37\lib\site-packages\marshmallow\fields.py", line 166, in __init__
    raise ValueError("'missing' must not be set for required fields.")
ValueError: 'missing' must not be set for required fields.
```

marshmallow 3.0.0rc4
marshmallow-dataclass 0.5.0

**Comment by lovasoa** [comment]
Hello @KoHcoJlb , and thank you for testing this project.

marshmallow 3 has not been released yet. `marshmallow-dataclass` interacts with marshmallow `2.x`.

Moreover, your dataclass declaration is invalid: you declared the field id as being of type `str`, but gave it a default of `None` (which is not an `str`). The type of the field should be `Optional[str]`.

**Comment by lovasoa** [comment]
I published [a pre-release on pypi supporting marshmallow 3](https://pypi.org/project/marshmallow-dataclass/6.0.0b2/). You can add it to your dependencies with 

```
pip install marshmallow-dataclass==6.0.0b2
```

**Comment by KoHcoJlb** [comment]
> 
> 
> I published [a pre-release on pypi supporting marshmallow 3](https://pypi.org/project/marshmallow-dataclass/6.0.0b2/). You can add it to your dependencies with
> 
> ```
> pip install marshmallow-dataclass==6.0.0b2
> ```

Thank you for your help.
I can't install this version.
```
Collecting marshmallow-dataclass==6.0.0b2
  Using cached https://files.pythonhosted.org/packages/46/9f/24ce999a3e45caf0619f0173ff29fcad0f12d67fa0cb00b73adba490979b/marshmallow_dataclass-6.0.0b2-py3-none-any.whl
Collecting marshmallow<4.0,>=3.0 (from marshmallow-dataclass==6.0.0b2)
  Could not find a version that satisfies the requirement marshmallow<4.0,>=3.0 (from marshmallow-dataclass==6.0.0b2) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.7.0, 1.0.0a0, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 2.0.0a1, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0b5, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.6.0, 2.6.1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4, 2.10.5, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.12.2, 2.13.0, 2.13.1, 2.13.2, 2.13.3, 2.13.4, 2.13.5, 2.13.6, 2.14.0, 2.15.0, 2.15.1, 2.15.2, 2.15.3, 2.15.4, 2.15.5, 2.15.6, 2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.17.0, 2.18.0, 3.0.0a1, 3.0.0b1, 3.0.0b2, 3.0.0b3, 3.0.0b4, 3.0.0b5, 3.0.0b6, 3.0.0b7, 3.0.0b8, 3.0.0b9, 3.0.0b10, 3.0.0b11, 3.0.0b12, 3.0.0b13, 3.0.0b14, 3.0.0b15, 3.0.0b16, 3.0.0b17, 3.0.0b18, 3.0.0b19, 3.0.0b20, 3.0.0rc1, 3.0.0rc2, 3.0.0rc3, 3.0.0rc4)
No matching distribution found for marshmallow<4.0,>=3.0 (from marshmallow-dataclass==6.0.0b2)
```

**Comment by lovasoa** [comment]
Because marshmallow 3.0.0 has not been released yet. I am going to upload a new version that is compatible with marshmallow `3.0.0rc4`, so you can use it immediately.
But anyway, it would be safer for you to work only with released versions.

**Comment by lovasoa** [comment]
Here it is: https://pypi.org/project/marshmallow-dataclass/6.0.0b3/
