### ISSUE TITLE
No support for types declared with `NewType`

### ISSUE THREAD

**Issue by karlb** [lovasoa/marshmallow_dataclass#5]
## Problem

Using types declares via `NewType` (https://docs.python.org/3/library/typing.html#newtype) causes marshmallow_dataclass to throw an error on import:
```
Traceback (most recent call last):
  File "type_ex.py", line 8, in <module>
    @dataclass
  File "/home/karl/tools/venv-services/lib/python3.7/site-packages/marshmallow_dataclass/__init__.py", line 77, in dataclass
    return add_schema(dataclasses.dataclass(clazz))
  File "/home/karl/tools/venv-services/lib/python3.7/site-packages/marshmallow_dataclass/__init__.py", line 93, in add_schema
    clazz.Schema = class_schema(clazz)
  File "/home/karl/tools/venv-services/lib/python3.7/site-packages/marshmallow_dataclass/__init__.py", line 193, in class_schema
    for field in fields
  File "/home/karl/tools/venv-services/lib/python3.7/site-packages/marshmallow_dataclass/__init__.py", line 194, in <dictcomp>
    if field.init
  File "/home/karl/tools/venv-services/lib/python3.7/site-packages/marshmallow_dataclass/__init__.py", line 284, in field_for_schema
    nested = forward_reference or class_schema(typ)
  File "/home/karl/tools/venv-services/lib/python3.7/site-packages/marshmallow_dataclass/__init__.py", line 185, in class_schema
    raise TypeError(f"{clazz.__name__} is not a dataclass and cannot be turned into one.")
TypeError: Barlike is not a dataclass and cannot be turned into one.
karl@t480karl:~/raiden-services (master)$

```

## Example:

```python
from typing import NewType
from marshmallow_dataclass import dataclass

T_Barlike = int
Barlike = NewType('Barlike', T_Barlike)


@dataclass
class Foo:
    bar: Barlike
```

## Expected behaviour:
Either treat the type like its base type or provide a way to register converters to a basic python type.

**Comment by karlb** [comment]
Thanks for the quick update!
