### ISSUE TITLE
marshmallow-oneofschema support

### ISSUE THREAD

**Issue by ffarella** [lovasoa/marshmallow_dataclass#62]
Hi!
Looks like a great lib!
Do you have any plans to support marshmallow-oneofschema?
see issue: https://github.com/marshmallow-code/marshmallow-oneofschema/issues/100

**Comment by lovasoa** [comment]
We do already support [marshmallow-union](https://python-marshmallow-union.readthedocs.io/en/latest/usage.html), when you install the library with `pip install marshmallow-dataclass[union]`.

It has the advantage of being completely transparent, you just specify the type of your data as `Union[TypeA, TypeB]`, and do not have to add a specific `type` field to your data. If you need a `type` field anyway (for backward compatibility or to avoid ambiguities), you can simply add it together with a validation function that compares its value to the type name.

**Comment by lovasoa** [comment]
Here is a quick example of how to handle ambiguous classes:

```py
from marshmallow_dataclass import dataclass
from dataclasses import field
from typing import List, Union
from marshmallow.validate import Equal

@dataclass
class Vector:
    type: str = field(metadata={"validate": Equal("Vector")})
    x: float
    y: float

@dataclass
class Point:
    type: str = field(metadata={"validate": Equal("Point")})
    x: float
    y: float


@dataclass
class Geometries:
    elements: List[Union[Point, Vector]]

pts = Geometries.Schema().load({"elements": [
    {"type":"Point", "x": 1, "y": 1},
    {"type":"Vector", "x": 1, "y": 1},
]})

print(pts)
```

But I found out that in practice, this is only rarely needed.

**Comment by ekhahniii** [comment]
@lovasoa thanks for the insightful example. Is there an approach that does not require each dataclass to "know" that it will be used in an ambiguous/polymorphic setting?

**Comment by lovasoa** [comment]
You could for instance wrap such a class into another one that would add the disambiguation field. You can flatten the parent class and the child with marshmallow if necessary.

**Comment by gbalke** [comment]
@lovasoa I'm trying to do this but with inheritance and running into trouble. To minimally change a working example, I'll modify the one you gave:

```python
from marshmallow_dataclass import dataclass
from dataclasses import field
from typing import List, Union
from marshmallow.validate import Equal

@dataclass
class Vector:
    type: str = field(metadata={"validate": Equal("Vector")})
    x: float
    y: float

@dataclass
class Point(Vector):
    type: str = field(metadata={"validate": Equal("Point")})

@dataclass
class Geometries:
    elements: List[Union[Point, Vector]]

pts = Geometries.Schema().load({"elements": [
    {"type":"Point", "x": 1, "y": 1},
    {"type":"Vector", "x": 1, "y": 1},
]})

print(pts)
```

This does not work and errors with:
```bash
Traceback (most recent call last):
  File "oneof.py", line 23, in <module>
    {"type":"Vector", "x": 1, "y": 1},
  File "/home/{user}/.local/lib/python3.6/site-packages/marshmallow_dataclass/__init__.py", line 466, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/home/{user}/.local/lib/python3.6/site-packages/marshmallow/schema.py", line 723, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/home/{user}/.local/lib/python3.6/site-packages/marshmallow/schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'elements': {0: {'type': ['Must be equal to Vector.']}}}
```
Is there a way to do this? Thank you in advance!

**Comment by pshirshov** [comment]
Just in case, while `Schema#load` works with your example, `Schema#dump` fails to serialize `elements` field properly. Such a shame :(

**Comment by activeperception** [comment]
This also works for marshmallow-dataclass 0.6.6 (I only tried the load method)

```python
import marshmallow.fields as f

from dataclasses import field, dataclass
from typing import List, Union

import marshmallow_dataclass
from marshmallow_oneofschema import OneOfSchema


@dataclass
class Vector:
    x: float
    y: float


@dataclass
class Point:
    x: float
    y: float
    z: float


class BaseSchema(OneOfSchema):
    type_schemas = {"Vector": marshmallow_dataclass.class_schema(Vector),
                    "Point": marshmallow_dataclass.class_schema(Point)}


@dataclass
class Geometries:
    elements: List[Union[Point, Vector]] = field(metadata={'marshmallow_field': f.List(f.Nested(BaseSchema))})


pts = marshmallow_dataclass.class_schema(Geometries)().load({"elements": [
    {"type": "Point", "x": 1, "y": 1, "z": 22},
    {"type": "Vector", "x": 1, "y": 1},
]})

print(pts)
```

**Comment by angelarosario** [comment]
@activeperception This works for me as well. Thanks for the example!

**Comment by hmnid** [comment]
Yeah, this approach with explicitly defined field works fine, but it completely ignores `base_schema` passed to `class_schema()` and there is no workaround here. 
We use same dataclass in two different contexts: 
1. snake_case api
1. camelCase api 
Camelization is done with appropriate base schema, like: `class_schema(MyDataclass, base_schema=CamelCaseSchema)`. Neat, hah? If we use OneOfSchema with explicit marshmallow_field, we are in trouble. Fine, fine, I guess we should fall back to mm-dataclass' union field and pray there will be no ambiguous data in practice.

**Comment by dairiki** [comment]
> this is rather verbose, is `typing.Literal` supported?

Yes, based on a look at [the source code](https://github.com/lovasoa/marshmallow_dataclass/blob/792dc6606dc0744b4457f151d6f8516e8d81e59e/marshmallow_dataclass/__init__.py#L662), there is support for `Literal` types. (It looks like this was added in #110.) Have you tried it?
