### ISSUE TITLE
recursive, self referencing dataclasses

### ISSUE THREAD

**Issue by marengaz** [lovasoa/marshmallow_dataclass#97]
hi all

i wonder if anyone has experience using a recursive structure? here's a demo script:
```
# from __future__ import annotations
import dataclasses
from dataclasses import dataclass
import marshmallow_dataclass

@dataclass
class StrLinkedList:
    head: str
    tail: "StrLinkedList"

sll = StrLinkedList(
    head="blah",
    tail=StrLinkedList("blah2", None)
)
print(sll)
print(dataclasses.asdict(sll))

SLLSchema = marshmallow_dataclass.class_schema(StrLinkedList)
sll_dict = SLLSchema().dump(sll)
print(sll_dict)
```

error text:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/dataclasses.py", line 1031, in fields
    fields = getattr(class_or_instance, _FIELDS)
AttributeError: 'str' object has no attribute '__dataclass_fields__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marengaz/pyenv/policy_tags_to_bq/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 288, in _proxied_class_schema
    fields: Tuple[dataclasses.Field, ...] = dataclasses.fields(clazz)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/dataclasses.py", line 1033, in fields
    raise TypeError('must be called with a dataclass type or instance')
TypeError: must be called with a dataclass type or instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marengaz/pyenv/policy_tags_to_bq/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 291, in _proxied_class_schema
    return class_schema(dataclasses.dataclass(clazz), base_schema)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/dataclasses.py", line 1019, in dataclass
    return wrap(cls)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/dataclasses.py", line 1011, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/dataclasses.py", line 814, in _process_class
    if cls.__module__ in sys.modules:
AttributeError: 'str' object has no attribute '__module__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marengaz/policy_tags_to_bq/test_marshmallow.py", line 20, in <module>
    SLLSchema = marshmallow_dataclass.class_schema(StrLinkedList)
  File "/Users/marengaz/pyenv/policy_tags_to_bq/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 278, in class_schema
    return _proxied_class_schema(clazz, base_schema)
  File "/Users/marengaz/pyenv/policy_tags_to_bq/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 304, in _proxied_class_schema
    attributes.update(
  File "/Users/marengaz/pyenv/policy_tags_to_bq/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 307, in <genexpr>
    field_for_schema(
  File "/Users/marengaz/pyenv/policy_tags_to_bq/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 491, in field_for_schema
    nested_schema or forward_reference or class_schema(typ, base_schema=base_schema)
  File "/Users/marengaz/pyenv/policy_tags_to_bq/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 278, in class_schema
    return _proxied_class_schema(clazz, base_schema)
  File "/Users/marengaz/pyenv/policy_tags_to_bq/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 293, in _proxied_class_schema
    raise TypeError(
TypeError: 'StrLinkedList' is not a dataclass and cannot be turned into one.
```

python dataclass supports this, but it seems like marshmallow_dataclass does not. ive tried various combinations of importing `__future__.annotations`, double quoting `tail: "StrLinkedList"` and playing with field() options to no avail.

is it possible?
thanks!

**Comment by marengaz** [comment]
sorry, dupe of #13 !

**Comment by lovasoa** [comment]
Your type annotation is incorrect. The type of tail is not LinkedList, it's Optional[LinkedList]
